name: Notify Telegram on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        REPO_NAME: ${{ github.repository }}
        COMMIT_AUTHOR: ${{ github.actor }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text="Nuovo push su repository $REPO_NAME\nAutore: $COMMIT_AUTHOR\nMessaggio: $COMMIT_MESSAGE\n[Link al commit](${{ github.event.head_commit.url }})"
